### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by lfreneda** [nfscan/ocr-process-service#10]
```
2017-01-03 00:06:29,103 - root - DEBUG - Running Cuneiform (sh) tool
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ryuk/lfreneda/work/others/ocr-process-service/service/ocr.py", line 103, in run
    lang=self.lang
  File "/usr/local/lib/python2.7/dist-packages/pyocr/cuneiform.py", line 114, in image_to_string
    proc.stdin.write(img_data.getvalue())
IOError: [Errno 32] Broken pipe
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ryuk/lfreneda/work/others/ocr-process-service/service/ocr.py", line 103, in run
    lang=self.lang
  File "/usr/local/lib/python2.7/dist-packages/pyocr/cuneiform.py", line 114, in image_to_string
    proc.stdin.write(img_data.getvalue())
IOError: [Errno 32] Broken pipe
```

Can u help me out?

**Comment by PauloMigAlmeida** [comment]
Hi @lfreneda,

Sorry for my late reply, I must have missed you issue email somehow. 

If you take a closer look at portion of the stack trace you provided, you might realize that it was the cuneiform binary which failed to respond correctly. This has usually 2 main reasons:

1. You have installed cuneiform without providing the ImageMagick++ header files dependency. (And for that reason you can't use any other image format different from bmp. I highly recommend you to install it using this library since it allows cuneiform to be way more efficient given the size of a PNG/JPEG when compared to a bmp file.

2. Cuneiform is well known for some incompatibilities when running on a 64-bit OS (yes, you read it correct). Honestly speaking, cuneiform was conceived in 1992 and many of its source code haven't been adapted to 64-bit instructions. You have some alternatives to workaround this issue though:

    1. You can install it using the ia32-libs which allows you to have multi-arch applications within the same OS. However, many of the distributions have deprecated it already.
    2. You can use a 32 instance (AWS still have a few AMIs available for that purpose)

```
File "/usr/local/lib/python2.7/dist-packages/pyocr/cuneiform.py", line 114, in image_to_string
    proc.stdin.write(img_data.getvalue())
IOError: [Errno 32] Broken pipe
```

Best regards,

Paulo Almeida
